5º Semestre/Programação V/cat-contato/src/br/org/catolicasc/entity/Contato.java
package br.org.catolicasc.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import br.org.catolicasc.interfaces.Bean;

@Entity
public class Contato implements Bean{

	@Id
	@GeneratedValue
	private Long id;
	
	private String nome;
	
	private String email;
	
	//@OneToOne
	private String endereco;
	
	private String dataNascimento;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public String getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(String dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	

	
 
}

5º Semestre/Programação V/cat-contato/src/br/org/catolicasc/controller/ContatoBean.java
package br.org.catolicasc.controller;

import java.util.List;

import javax.faces.bean.ManagedBean;

import br.org.catolicasc.dao.ContatoDao;
import br.org.catolicasc.entity.Contato;

@ManagedBean
public class ContatoBean {

	private Contato contato = new Contato();
	private ContatoDao contatoDao = new ContatoDao();

	public List<Contato> getContatos() {
		return this.contatoDao.listaTodos();
	}

	public Contato getContato() {
		return contato;
	}

	public void setContato(Contato contato) {
		this.contato = contato;
	}

	public String salva() {
		this.contatoDao.salva(this.contato);
		this.contato = new Contato();
		return "listaContatos.xhtml?faces-redirect=true";
	}

	public void exclui(Contato contato) {
		this.contatoDao.remove(contato);
	}

	public String edita(Contato contato) {
		this.contato = contato;
		return "cadastraContatos.xhtml";

	}

}

5º Semestre/Programação V/cat-contato/src/br/org/catolicasc/interfaces/Bean.java
package br.org.catolicasc.interfaces;

public interface Bean {

	Long getId();
	void setId(Long id);
}

5º Semestre/Programação V/cat-contato/WebContent/cadastraContatos.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">

<h:body>
	<h:form>
		<h:panelGrid columns="2">
		Id: <h:inputText value="#{contatoBean.contato.id}" />
		Nome: <h:inputText value="#{contatoBean.contato.nome}" />
		Email: <h:inputText value="#{contatoBean.contato.email}" />
		Data de nascimento: <h:inputText
				value="#{contatoBean.contato.dataNascimento}" />
		Endereço: <h:inputText value="#{contatoBean.contato.endereco}" />

			<h:commandButton value="Salvar" action="#{contatoBean.salva}" />
		</h:panelGrid>
	</h:form>

</h:body>

</html>

5º Semestre/Programação V/cat-contato/WebContent/listaContatos.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:body>
		<h:form>
		<h:dataTable value="#{contatoBean.contatos}" 
		var="contato" border="1">
			<h:column>
				<f:facet name="header">ID</f:facet>
				#{contato.id}
			</h:column>
			<h:column>
				<f:facet name="header">Nome</f:facet>
				#{contato.nome}
			</h:column>
			<h:column>
				<f:facet name="header">E-mail</f:facet>			
				#{contato.email}
			</h:column>
			<h:column>
				<f:facet name="header">Data de Nascimento</f:facet>
				#{contato.dataNascimento}
			</h:column>
			<h:column>
				<f:facet name="header">Endereço</f:facet>
				#{contato.endereco}
			</h:column>
			<!--  aula 14 -->
			<h:column>
				<f:facet name="header">Ações</f:facet>
				<h:commandLink value="Exclui"
				 action="#{contatoBean.exclui(contato)}" /> |
				<h:commandLink value="Edita"
				 action="#{contatoBean.edita(contato)}" /> 				  
			</h:column>
			<!--  aula 14 -->
		</h:dataTable>
		</h:form>
	</h:body>
</html>